# Generated by Django 3.2.9 on 2021-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default='default_book.pdf', upload_to='media/book_files'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/book_pics'),
        ),
    ]
