# Generated by Django 3.2.9 on 2021-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20211107_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default='default_book.pdf', upload_to='book_files'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_pics'),
        ),
    ]
